name: Aqua Engine

on: [ push, pull_request ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows",
            os: windows-latest,
            artifact: "AquaEngine_Windows.zip"
          }
        - {
            name: "Linux",
            os: ubuntu-latest,
            artifact: "AquaEngine_Linux.txz"
          }
        - {
            name: "MacOS",
            os: macos-latest,
            artifact: "AquaEngine_MacOS.txz"
          }

    # Get source
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    # Install pre-requisites
    - uses: lukka/get-cmake@latest

    - if: matrix.config.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xorg-dev

    - name: VCPKG
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgDirectory: '${{ github.workspace }}/Engine/Vendor/vcpkg'

    # Set CMake configuration based on branch
    - if: github.ref == 'refs/head/main'
      run: echo "CMAKE_CONFIG=Release" >> $GITHUB_ENV

    - if: github.ref != 'refs/head/main'
      run: echo "CMAKE_CONFIG=RelWithDebInfo" >> $GITHUB_ENV

    # Set binary directory based on OS
    - if: matrix.config.os == 'windows-latest'
      run: |
        "BINARY_DIR=${{ github.workspace }}/build/bin/${{ env.CMAKE_CONFIG }}"

    - if: matrix.config.os != 'windows-latest'
      run: |
        "BINARY_DIR=${{ github.workspace }}/build/bin/"

    # Configure CMake
    - name: Configure
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.CMAKE_CONFIG }}

    # Build
    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.CMAKE_CONFIG }}

    # Test
    - name: Run Test
      run: $BINARY_DIR/AquaEngineTest

    # Read engine version from text file
    - uses: juliangruber/read-file-action@v1
      id: readFile
      with:
        path: ./Version.txt

    # Copy desired artifacts to output folder
    - run: |
        mkdir -p ${{ github.workspace }}/build/artifact
        cp $BINARY_DIR/BaseGame* ${{ github.workspace }}/build/artifact/
        cp -r ${{ github.workspace }}/Apps/Assets/ ${{ github.workspace }}/build/artifact/Assets/
        cp $BINARY_DIR/*.so ${{ github.workspace }}/build/artifact/
        cp $BINARY_DIR/*.dll ${{ github.workspace }}/build/artifact/

    # Upload artifact
    - uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: ${{ matrix.config.artifact }}-${{ steps.readFile.outputs.content }}
        path: ${{ github.workspace }}/build/lib/*
